dist: trusty
sudo: false
language: generic
matrix:
  include:
    - os: linux
      language: python
      python: "3.5"
    - os: linux
      language: python
      python: "3.6"
    - os: linux
      language: python
      python: "3.6-dev"
    - os: linux
      language: python
      python: "3.7-dev"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.5.3"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.6.1"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.6-dev"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.7-dev"
  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"
    - env: TRAVIS_PYTHON_VERSION="3.6-dev"
    - env: TRAVIS_PYTHON_VERSION="3.7-dev"

before_install: |
  set -e
  if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    brew update
    brew install pyenv || brew upgrade pyenv
    pyenv install "${TRAVIS_PYTHON_VERSION}"
    export PATH="$HOME/.pyenv/versions/${TRAVIS_PYTHON_VERSION}/bin:${PATH}"
  fi
  set +e

install:
  - python --version
  - pip --version
  - pip install -U pip
  - pip install -U -r dev_requirements.txt

script:
  - TEST_PACKAGING=1 python -m coverage run --branch --source . -m unittest discover --verbose
  - pip install -U -r optional_requirements_ci.txt
  - python -m coverage run --append --branch --source . -m unittest discover --verbose

after_success:
  - python -m pylint --load-plugins=pylint.extensions.mccabe --docstring-min-length 5 --no-docstring-rgx "^(test)?_|.*Tests$" --unsafe-load-any-extension y --output-format colorized  --reports y $(find . -name "*.py")
  - python -m coverage report --show-missing
  - codecov

notifications:
  slack:
    secure: "GYQpySSGAFOQwxgsz7obx4QBhnRXxv0FWz0KN1ZoYBp6wnainTjAro+BAUEcYSNe4dBjJ6qEn0gPe1Pq0yMn7fJko/z7Gmkg0Jk9S4aGFU3JWQm0kV7hDUX6simdBTYV/jAl5lncvMihjjDqqOWlp7yFMEvaNe3vZk8y2NljpDAy5wbSe1BPFK+vd20uwKnIMdv1ejyDPqf860Kouz8tujizopvP8kz4phBaRVdkD60ysZZhh4zY7HSxs8SMTPSMLKpXyd4Xk0Uy3t0j6LQky6oEFy5xWQYd+PhBpVKawa8KZqEx6xG4ChBtK9OamcsOUS11sZyE4RBnmjkXx05OZdBjj/ow6ReRwUJzjEPcfMg+qlsDkHGKPjwF3hm6onC04IpHTF/i3Tde1yRDBTOSBSQQ+QqKrbc4txv95anqV4UHJf1HssDRS3uHKRuQJkN+XEgdARQMYKeIjw3+R1hqxfffLfn2zGhV9YkHuKJ/kurJ5LeTn66Fe6qfKu9pjJk7cIdydt4u9+uEMd+L60vdtzqoqyBnlq8I7JWK1EuNqc2W/UFpPKteQW57QZlQoLTz7N5T8/YBlKec+ZxX/oKZiKMruhK3m4S27OGDlC9IwtX1ZOaYJ0BcDz4caFKiDqWDW+QsM7Vyvko3N1uacL3cclLcCsQ7mjcwMSEsdjdAV5c="
  email: false
