version: "{build}"

environment:
  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

init:
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

install:
  - pip install -U pip
  - pip install -U -r dev_requirements.txt

build: off

test_script:
  - set TEST_PACKAGING=1
  - python -m coverage run --branch --source . -m unittest discover --verbose
  - pip install -U -r optional_requirements_ci.txt
  - python -m coverage run --append --branch --source . -m unittest discover --verbose

after_test:
  - python -m coverage report --show-missing
  - codecov
  - dir /a-d /b /s *.py
